# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted', models.BooleanField(default=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.UserBlogdom')),
            ],
        ),
    ]
