# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 20, 10, 48, 431000, tzinfo=utc), editable=False),
        ),
    ]
