# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 12, 21, 38, 951000, tzinfo=utc), editable=False),
        ),
    ]
