# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_upvotedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogdom',
            name='email',
            field=models.EmailField(default='gargsarthak30@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
