# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20161001_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 18, 25, 39, 663000, tzinfo=utc), editable=False),
        ),
    ]
