# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:10
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_userblogdom_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogdom',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.content_cover_picture),
        ),
    ]
