# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20161005_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 18, 29, 3, 417000, tzinfo=utc), editable=False),
        ),
    ]
