# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_userblogdom_cover_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblogdom',
            name='email',
        ),
    ]
