# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_userblogdom_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
    ]
